# Generated by Django 4.2.7 on 2023-11-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_alter_habit_reward_alter_habit_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='time_to_complete',
            field=models.PositiveIntegerField(default=2, verbose_name='Время на выполнение в секундах'),
        ),
    ]
